In [1]:
# import libraries

%matplotlib notebook
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
from sklearn.dummy import DummyClassifier
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_curve, auc
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score
from adspy_shared_utilities import plot_class_regions_for_classifier_subplot
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_recall_curve
from adspy_shared_utilities import plot_class_regions_for_classifier
from sklearn.svm import SVC



In [2]:
# Week 3: 
# Model Evaluation & Selection, Evaluation Metrics in ML
# Evaluation metric: accuracy(score), precision, recall, F1

# Dummy Classifiers 
# Confusion Matrix:  Binary Prediction Outcomes
# Evaluation metrics for binary classification
# Decision Functions (of probability)
# Precision-Recall curves and ROC curves
# GridSearch

In [3]:
# Week 3: Dummy Classifiers 

In [4]:
# y_binary_imbalanced = y.copy()
# y_binary_imbalanced[y_binary_imbalanced != 1] = 0


# dummy_majority = DummyClassifier(strategy = 'strategy').fit(X_train, y_train)

# types of DummyClassifier strategy parameter:
# most frequent: predicts most frequent label in train-set
# stratified: random predictions based on train-set distribution of classes
# uniform: predictions are uniformly at random
# constant: always predicts the same label constant given by user

# get confusion matrix 
# confusion = confusion_matrix(y_test, y_majority_predicted_from_model)

In [5]:
# Week 3: Dummy Classifiers
# create DummyClassifier: DONT look at data-sets to do predictions
# use strategy or rule-of-thumb
# for inbalanced classification, dont use accuracy rather other methods

In [6]:
# Model Evaluation & Selection
# 1. choose evaluation methods that match the goal of application
# 2. run evaluation metrics for multiple models
# 3. select model with best value of evaluation from metrics

In [7]:
# accuracy = #correct predictions/#total predictions

In [8]:
%matplotlib notebook
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

# load source data 
dataset = load_digits()

# divide source data in X data and y target 
X, y = dataset.data, dataset.target

# get  data 
for class_name, class_count in zip(dataset.target_names, np.bincount(dataset.target)):
    print(class_name,class_count)

0 178
1 182
2 177
3 183
4 181
5 182
6 181
7 179
8 174
9 180


In [9]:
# Creating a dataset with imbalanced binary classes:  
# Negative class (0) is 'not digit 1' 
# Positive class (1) is 'digit 1'

# label digits, 0='not digit 1'  1='digit 1'
y_binary_imbalanced = y.copy()
y_binary_imbalanced[y_binary_imbalanced != 1] = 0

print('Original labels:\t', y[1:30])
print('New binary labels:\t', y_binary_imbalanced[1:30])

Original labels:	 [1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
New binary labels:	 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


In [10]:
np.bincount(y_binary_imbalanced)    # Negative class (0) is the most frequent class

array([1615,  182], dtype=int64)

In [11]:
# divide X, y data into train-set and test-set

X_train, X_test, y_train, y_test = train_test_split(X, y_binary_imbalanced, random_state=0)

# Accuracy of Support Vector Machine classifier
from sklearn.svm import SVC

# create SVectorMachine model, parameters: kernel function='rbf', C=1
# fit/train model with train-set
svm = SVC(kernel='rbf', C=1).fit(X_train, y_train)

svm.score(X_test, y_test)

0.9955555555555555

In [12]:
from sklearn.dummy import DummyClassifier

# create DummyClassifier: DONT look at data-sets to do predictions
# use strategy or rule-of-thumb
# provides no accuracy base line, always picks most frequent class
#  check on comparison, null comparison


# Negative class (0) is most frequent
dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train, y_train)

# types of DummyClassifier strategy parameter:
# most frequent: predicts most frequent label in train-set
# stratified: random predictions based on train-set distribution of classes
# uniform: predictions are uniformly at random
# constant: always predicts the same label constant given by user



# Therefore the dummy 'most_frequent' classifier always predicts class 0
y_dummy_predictions = dummy_majority.predict(X_test)

y_dummy_predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [13]:
# score/measure performance of DummyClassifier
dummy_majority.score(X_test, y_test)

0.9044444444444445

In [14]:
svm = SVC(kernel='linear', C=1).fit(X_train, y_train)
svm.score(X_test, y_test)

0.9777777777777777

In [15]:
# Confusion Matrix outputs:  Binary Prediction Outcomes
# output Negative: True negative TN, False positive FP
# output Postive: False negative FN, True positive TP

In [16]:
# Confusion Matrix

from sklearn.metrics import confusion_matrix

# Negative class (0) is most frequent

# create DummyClassifier, parameters:strategy = 'most_frequent', fit/train with train-set 
dummy_majority = DummyClassifier(strategy = 'most_frequent').fit(X_train, y_train)

# dummy_majority.predict(X_test), most frequent majority predicted output
# from X_test data
y_majority_predicted = dummy_majority.predict(X_test)

# get confusion matrix 
confusion = confusion_matrix(y_test, y_majority_predicted)

print('Most frequent class (dummy classifier)\n', confusion)

Most frequent class (dummy classifier)
 [[407   0]
 [ 43   0]]


In [17]:
# produces random predictions w/ same class proportion as training set

# create DummyClassifier, parameters:strategy='stratified'(random predictions based on train-set distribution of classes)
dummy_classprop = DummyClassifier(strategy='stratified').fit(X_train, y_train)

# get y target predicted by DummyClassifier, random predictions based on train-set classes distri
# random output in proportion to ratio of labels in train-set



y_classprop_predicted = dummy_classprop.predict(X_test)
confusion = confusion_matrix(y_test, y_classprop_predicted)
print(y_classprop_predicted)
print('Random class-proportional prediction (dummy classifier)\n', confusion)

[0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1
 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0]
Random class-proportional prediction (dummy classifier)
 [[361  46]
 [ 37   6]]


In [18]:
# create SVectorMachine model, parameters: kernel function='linear', C=1
svm = SVC(kernel='linear', C=1).fit(X_train, y_train)
svm_predicted = svm.predict(X_test)
confusion = confusion_matrix(y_test, svm_predicted)
print(svm_predicted)
print('Support vector machine classifier (linear kernel, C=1)\n', confusion)

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1
 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0
 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 1 0 0 0 1 0]
Support vector machine classifier (linear kernel, C=1)
 [[402   5]
 [  5  38]]


In [19]:
from sklearn.linear_model import LogisticRegression

# create LogisticRegression, standard default parameters
lr = LogisticRegression().fit(X_train, y_train)
lr_predicted = lr.predict(X_test)
confusion = confusion_matrix(y_test, lr_predicted)

print('Logistic regression classifier (default settings)\n', confusion)

Logistic regression classifier (default settings)
 [[401   6]
 [  8  35]]


C:\Users\Diego\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
from sklearn.tree import DecisionTreeClassifier

# create DecisionTreeClassifier model, parameters: max_depth=2 
dt = DecisionTreeClassifier(max_depth=2).fit(X_train, y_train)
tree_predicted = dt.predict(X_test)
confusion = confusion_matrix(y_test, tree_predicted)

print('Decision tree classifier (max_depth = 2)\n', confusion)

Decision tree classifier (max_depth = 2)
 [[400   7]
 [ 17  26]]


In [21]:
# Week 3: Evaluation metrics for binary classification
# Analysis Classification Performance

# always look at the confusion matrix of the classifier model


# Accuracy = (TN+TP)/(TOTAL): ratio of correct classifications to total
# ClassificationError = (FP+FN)/(TOTAL) = 1-accuracy:  ratio of incorrect classifications to total
# Recall = TruePositiveRate/Sensitivity/ProbDetection =  TP/(TP+FN): ratio of positive correct classifications to total TP+FN
# Precision = TP/(TP+FP): ratio of true positive predictions to total positive predictions
# FPR FalsePositiveRate/Specificity = FP/(TN+FP) ratio of false positive predictions to total negative predictions
# F1 score = 2*(Precision*Recall)/(Precision+Recall)= 2TP/(2TP+FN+FP), combining precision and recall

In [22]:
# accuracy = accuracy_score(y_test, y_model_predicted)
# precision = precision_score(y_test, y_model_predicted)
# recall = recall_score(y_test, y_model_predicted)
# f1 score = f1_score(y_test, y_model_predicted)

# classification_report(y_test, model_predicted, target_names= y_target_labels)

In [23]:
# Evaluation metrics Trade-offs: DEPENDS on the application of the model
# High Precision- Low Recall: more true postive classifications of total positive predictions,
# more true positive classifications predicted as negative(incorrectly classified)
# narrow decision boundary
# applications: query suggestions, document classification, many-customer facing tasks, users and customers



# Low Precision - High Recall: lower true positive classifications predicted as negative(false negative),
# lower true postive classifications of total positive predictions
# wide decision boundary
# applications: tumor detection, legal applications

In [24]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
# Accuracy = TP + TN / (TP + TN + FP + FN)
# Precision = TP / (TP + FP)
# Recall = TP / (TP + FN)  Also known as sensitivity, or True Positive Rate
# F1 = 2 * Precision * Recall / (Precision + Recall) 

print('Accuracy: {:.2f}'.format(accuracy_score(y_test, tree_predicted)))
print('Precision: {:.2f}'.format(precision_score(y_test, tree_predicted)))
print('Recall: {:.2f}'.format(recall_score(y_test, tree_predicted)))
print('F1: {:.2f}'.format(f1_score(y_test, tree_predicted)))

Accuracy: 0.95
Precision: 0.79
Recall: 0.60
F1: 0.68


In [25]:
# Combined report with all above metrics
from sklearn.metrics import classification_report

print(classification_report(y_test, tree_predicted, target_names=['not 1', '1']))

              precision    recall  f1-score   support

       not 1       0.96      0.98      0.97       407
           1       0.79      0.60      0.68        43

    accuracy                           0.95       450
   macro avg       0.87      0.79      0.83       450
weighted avg       0.94      0.95      0.94       450



In [26]:
# DummyClassifier(null comparison), get evaluation metrics to compare

print('Random class-proportional (dummy)\n', 
      classification_report(y_test, y_classprop_predicted, target_names=['not 1', '1']))
print('SVM\n', 
      classification_report(y_test, svm_predicted, target_names = ['not 1', '1']))
print('Logistic regression\n', 
      classification_report(y_test, lr_predicted, target_names = ['not 1', '1']))
print('Decision tree\n', 
      classification_report(y_test, tree_predicted, target_names = ['not 1', '1']))

Random class-proportional (dummy)
               precision    recall  f1-score   support

       not 1       0.91      0.89      0.90       407
           1       0.12      0.14      0.13        43

    accuracy                           0.82       450
   macro avg       0.51      0.51      0.51       450
weighted avg       0.83      0.82      0.82       450

SVM
               precision    recall  f1-score   support

       not 1       0.99      0.99      0.99       407
           1       0.88      0.88      0.88        43

    accuracy                           0.98       450
   macro avg       0.94      0.94      0.94       450
weighted avg       0.98      0.98      0.98       450

Logistic regression
               precision    recall  f1-score   support

       not 1       0.98      0.99      0.98       407
           1       0.85      0.81      0.83        43

    accuracy                           0.97       450
   macro avg       0.92      0.90      0.91       450
weighted avg 

In [27]:
# Week 3:  Decision Functions (of probability)
# y_scores = model.fit(X_train, y_train).decision_function(X_test)
# y_proba = model.fit(X_train, y_train).predict_proba(X_test)

In [28]:
# provide info of uncertainty to a prediction, 
# decision_function or predict_proba

# decision_function: provides a classifier's score value, 
# how confidently classifier predicts.

# the positive class(large magnitude positive values),  entre más positivo, más probable que sea class I
# the negative class: large magnitude negative values,  entre más negativo, más probable que sea class II


# predict_proba: provides predicted probability of class membership
# binary classifier, is class with probability greater than 0.5
# default threshold> 0.50
# higher threshold(more conservative/confident classifier) increases precision, less errors in prediction


# chossing a decision threshold gives a classification rule
# sweeping decision threshold through range of possible score value,
# get a series of classification outcomes that generate the decision functions


# precision-recall curve: relación de evaluation metrics de modelos precision-recall curve 
# a variaciones de threshold

In [30]:
# load source data 
dataset = load_digits()

# divide source data in X data and y target 
X, y = dataset.data, dataset.target
# divide source data into train-set and test-set
X_train, X_test, y_train, y_test = train_test_split(X, y_binary_imbalanced, random_state=0)

# create LogisticRegression model, parameters: default
# get model score values with X_test
y_scores_lr = LinearRegression.fit(X_train, y_train)

#y_score_list = list(zip(y_test[0:20], y_scores_lr[0:20]))

# show the decision_function scores for first 20 instances
y_score_list

TypeError: fit() missing 1 required positional argument: 'y'

In [31]:
# load source data 
dataset = load_digits()

# divide source data in X data and y target 
X, y = dataset.data, dataset.target

# divide source data into train-set and test-set
X_train, X_test, y_train, y_test = train_test_split(X, y_binary_imbalanced, random_state=0)

# create LogisticRegression model, parameters: default.
# predict_proba(X_test) predict probability of X_test
y_proba_lr = lr.fit(X_train, y_train).predict_proba(X_test)



y_proba_list = list(zip(y_test[0:20], y_proba_lr[0:20,1]))

# show the probability of positive class for first 20 instances
y_proba_lr

C:\Users\Diego\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[1.00000000e+00, 1.11050346e-13],
       [9.99999996e-01, 3.82022220e-09],
       [1.00000000e+00, 2.08621900e-13],
       [1.00000000e+00, 3.59565900e-10],
       [1.00000000e+00, 1.46732887e-10],
       [9.99992541e-01, 7.45923532e-06],
       [1.50715898e-03, 9.98492841e-01],
       [1.00000000e+00, 7.19868273e-11],
       [1.00000000e+00, 1.09172098e-12],
       [1.00000000e+00, 2.10180784e-12],
       [1.00000000e+00, 1.45299315e-14],
       [1.00000000e+00, 1.71548681e-10],
       [1.00000000e+00, 1.01050539e-11],
       [9.99998461e-01, 1.53867898e-06],
       [9.99998716e-01, 1.28391853e-06],
       [9.99998340e-01, 1.66043709e-06],
       [5.12842655e-06, 9.99994872e-01],
       [1.00000000e+00, 1.19274177e-15],
       [9.99998207e-01, 1.79324010e-06],
       [1.00000000e+00, 1.40451715e-13],
       [1.00000000e+00, 3.05032183e-11],
       [9.99999849e-01, 1.50922547e-07],
       [1.00000000e+00, 6.76047110e-14],
       [9.99958766e-01, 4.12341603e-05],
       [1.000000

In [ ]:
# Precision-Recall curves and ROC curves
# precision, recall, thresholds = precision_recall_curve(y_test, y_scores_model) 
# fpr_lr, tpr_lr, _ = roc_curve(y_test, y_score_model)

In [ ]:
# Precision-Recall curve: Evaluation metrics curves and trade-offs
# ideal classifier: precision=recall=1
# entre más cerca el punto de threshold a top right, mejor
# steep of P-R curve: maximize precision while maximize recall


# ROC curve: reciving operating characteristic curves for binary classification
# x-False Positive Rate vs y-True Positive Rate
# ideal ROC point is top left X-False Positive Rate=0, y-True Positive=1
# steep of ROC curve: maximize true positive rate, while minimize the false positive rate


In [32]:
from sklearn.metrics import precision_recall_curve

# precision_recall_curve(y_test, y_scores_lr),
# create precision-recall curve,  parameters: y_test, y_model score values
precision, recall, thresholds = precision_recall_curve(y_test, y_scores_lr)

# get min(abs(threshold)) threshold minimo 
closest_zero = np.argmin(np.abs(thresholds))
# get min precision value at min threshold
closest_zero_p = precision[closest_zero]
# get min recall value at min thresholds
closest_zero_r = recall[closest_zero]

# plot
plt.figure()
plt.xlim([0.0, 1.01])
plt.ylim([0.0, 1.01])
plt.plot(precision, recall, label='Precision-Recall Curve')
plt.plot(closest_zero_p, closest_zero_r, 'o', markersize = 12, fillstyle = 'none', c='r', mew=3)
plt.xlabel('Precision', fontsize=16)
plt.ylabel('Recall', fontsize=16)
plt.axes().set_aspect('equal')
plt.show()

NameError: name 'y_scores_lr' is not defined

In [ ]:
from sklearn.metrics import roc_curve, auc

# divide source data into train-set and test-set
X_train, X_test, y_train, y_test = train_test_split(X, y_binary_imbalanced, random_state=0)

# get y_model score values from X_test 
y_score_lr = lr.fit(X_train, y_train).decision_function(X_test)

# create roc curve,  parameters: y_test, y_model score values
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_score_lr)
roc_auc_lr = auc(fpr_lr, tpr_lr)

plt.figure()
plt.xlim([-0.01, 1.00])
plt.ylim([-0.01, 1.01])
plt.plot(fpr_lr, tpr_lr, lw=3, label='LogRegr ROC curve (area = {:0.2f})'.format(roc_auc_lr))
plt.xlabel('False Positive Rate', fontsize=16)
plt.ylabel('True Positive Rate', fontsize=16)
plt.title('ROC curve (1-of-10 digits classifier)', fontsize=16)
plt.legend(loc='lower right', fontsize=13)
plt.plot([0, 1], [0, 1], color='navy', lw=3, linestyle='--')
plt.axes().set_aspect('equal')
plt.show()

In [ ]:
from matplotlib import cm

X_train, X_test, y_train, y_test = train_test_split(X, y_binary_imbalanced, random_state=0)

plt.figure()
plt.xlim([-0.01, 1.00])
plt.ylim([-0.01, 1.01])
for g in [0.01, 0.1, 0.20, 1]:
    svm = SVC(gamma=g).fit(X_train, y_train)
    y_score_svm = svm.decision_function(X_test)
    fpr_svm, tpr_svm, _ = roc_curve(y_test, y_score_svm)
    roc_auc_svm = auc(fpr_svm, tpr_svm)
    accuracy_svm = svm.score(X_test, y_test)
    print("gamma = {:.2f}  accuracy = {:.2f}   AUC = {:.2f}".format(g, accuracy_svm, 
                                                                    roc_auc_svm))
    plt.plot(fpr_svm, tpr_svm, lw=3, alpha=0.7, 
             label='SVM (gamma = {:0.2f}, area = {:0.2f})'.format(g, roc_auc_svm))

plt.xlabel('False Positive Rate', fontsize=16)
plt.ylabel('True Positive Rate (Recall)', fontsize=16)
plt.plot([0, 1], [0, 1], color='k', lw=0.5, linestyle='--')
plt.legend(loc="lower right", fontsize=11)
plt.title('ROC curve: (1-of-10 digits classifier)', fontsize=16)
plt.axes().set_aspect('equal')

plt.show()

In [ ]:
# Week 3: Multi-class Evaluation, extension of binary classification
# one class vs multiple class

# df_cm = pd.DataFrame(confusion_mc, index = [i for i in range(0,10)], columns = [i for i in range(0,10)])
# confusion_mc = confusion_matrix(y_test_mc, svm_predicted_mc)
# classification_report(y_test_mc, svm_predicted_mc)

# precision_score(y_test_mc, svm_predicted_mc, average = 'micro')
# precision_score(y_test_mc, svm_predicted_mc, average = 'macro')

In [ ]:
# General evaluation metrics are averaged across multiple classes
# multi-label classification: each instance can have multiple labels

# always look at the confussion matrix to see what kind of errors generate

# macro avg metric = SUM(metric of each class)
# micro avg metric = correct predictions/total prediction

# model with classes of about same number of instances, then macro=micro

# model with classes much larger than others, then:
# 1. for weight metric toward the largest ones, use micro
# 2. for weight metric toward the smallest ones, use macro

# if micro is much lower than macro, examine large classes for poor metric performance/score
# if macro is much lower than micro, examine small classes for poor metric performance/score

In [ ]:
# load source data 
dataset = load_digits()
# set X data, y target from source data
X, y = dataset.data, dataset.target

# divide source data in train-source and test-source
X_train_mc, X_test_mc, y_train_mc, y_test_mc = train_test_split(X, y, random_state=0)

# create SVectorMachine Linear Kernel, parameters: kernel function = 'linear', fit/train
svm = SVC(kernel = 'linear').fit(X_train_mc, y_train_mc)
# get y_predicted values for the model 
svm_predicted_mc = svm.predict(X_test_mc)

# get confusion matrix, parameters:y_test_mc, y_predicted_model
confusion_mc = confusion_matrix(y_test_mc, svm_predicted_mc)

# create DataFrame with confusion matrix
df_cm = pd.DataFrame(confusion_mc, 
                     index = [i for i in range(0,10)], columns = [i for i in range(0,10)])

# plot
plt.figure(figsize=(5.5,4))
sns.heatmap(df_cm, annot=True)
plt.title('SVM Linear Kernel \nAccuracy:{0:.3f}'.format(accuracy_score(y_test_mc, 
                                                                       svm_predicted_mc)))
plt.ylabel('True label')
plt.xlabel('Predicted label')


# create SVectorMachine RBF Kernel model, parameters: kernel func='RBF', fit/train
svm = SVC(kernel = 'rbf').fit(X_train_mc, y_train_mc)

# # get y_predicted values for the model with X_test test-set
svm_predicted_mc = svm.predict(X_test_mc)
# get confusion matrix (evaluation metrics)
confusion_mc = confusion_matrix(y_test_mc, svm_predicted_mc)
df_cm = pd.DataFrame(confusion_mc, index = [i for i in range(0,10)],
                  columns = [i for i in range(0,10)])
# plot
plt.figure(figsize = (5.5,4))
sns.heatmap(df_cm, annot=True)
plt.title('SVM RBF Kernel \nAccuracy:{0:.3f}'.format(accuracy_score(y_test_mc, 
                                                                    svm_predicted_mc)))
plt.ylabel('True label')
plt.xlabel('Predicted label');

In [ ]:
print(classification_report(y_test_mc, svm_predicted_mc))

In [ ]:
print('Micro-averaged precision = {:.2f} (treat instances equally)'
      .format(precision_score(y_test_mc, svm_predicted_mc, average = 'micro')))
print('Macro-averaged precision = {:.2f} (treat classes equally)'
      .format(precision_score(y_test_mc, svm_predicted_mc, average = 'macro')))

In [ ]:
print('Micro-averaged f1 = {:.2f} (treat instances equally)'
      .format(f1_score(y_test_mc, svm_predicted_mc, average = 'micro')))
print('Macro-averaged f1 = {:.2f} (treat classes equally)'
      .format(f1_score(y_test_mc, svm_predicted_mc, average = 'macro')))

In [ ]:
# Week 3: Metricas de evaluacion en Regression 

# r2_score(y_test, y_predict_model):  R2 ajuste del modelo lineal (mala métrica en el test-set)
# mean_squared_error(y_test,y_predict_model)):  MSE métrica optima, el ajuste de los parámetros de OLS es con MSE. La raíz cuadrada de la suma de errores en promedio
# mean_absolute_error(y_test,y_predict_model))
# median_abs_error(y_test,y_predict_model))

In [ ]:
#  trade-off  entre métricas de evaluación 
# Métricas de evaluación  graficadas en funciones 

In [ ]:
# RegresiónMétricas de evaluación:


# mean_absolute_error = abs(y_target-y_predicted) )
# mean_squared_error = (y_target-y_predicted)^2 
# median_abs_error = robust to outliers

In [ ]:
# DummyRegressors implements 4 simple baseline rules for regression
# mean: predicts the mean of the train-set y target values
# median: predicts the median of the train-set y target values
# quantile(porcentil): predicts a user quantile of the train-set y target values (75%)
# constant: predicts user constant value  

In [ ]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.dummy import DummyRegressor

# load source data
diabetes = datasets.load_diabetes()

# divide source data into X data and y target values
X = diabetes.data[:, None, 6]
y = diabetes.target

# divide data into train-set and test-set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# create LinearRegression() model, parameters: default
lm = LinearRegression().fit(X_train, y_train)

# create  DummyRegressor, parameters: mean predicts the mean of the train-set y target values
lm_dummy_mean = DummyRegressor(strategy = 'mean').fit(X_train, y_train)

# get y predicted values from LinearRegression model
y_predict = lm.predict(X_test)

# get y predicted values from DummyRegressor mean model
y_predict_dummy_mean = lm_dummy_mean.predict(X_test)

print('Linear model, coefficients: ', lm.coef_)
print("Mean squared error (dummy): {:.2f}".format(mean_squared_error(y_test, 
                                                                     y_predict_dummy_mean)))

print("Mean squared error (linear model): {:.2f}".format(mean_squared_error(y_test, y_predict)))
print("r2_score (dummy): {:.2f}".format(r2_score(y_test, y_predict_dummy_mean)))
print("r2_score (linear model): {:.2f}".format(r2_score(y_test, y_predict)))

# Plot outputs
plt.scatter(X_test, y_test,  color='black')
plt.plot(X_test, y_predict, color='green', linewidth=2)
plt.plot(X_test, y_predict_dummy_mean, color='red', linestyle = 'dashed', 
         linewidth=2, label = 'dummy')

plt.show()

In [ ]:
# Week 3: Selección de modelo, escoger mejor clasificador 
# cross_val_score(model, X_data, y_labels, cv=param):  validación cruzada  k-fold
# grid_search = GridSearchCV(model, param_grid = param_range, scoring = evaluation_metric ):  ***Clase para encontrar hiper parámetros óptimo 
# grid_search.fit(X_train, y_train)
# y_decision_fn_scores_eval = grid_search.decision_function(X_test):  retorna la función de decisión que son las probabilidades de pertenencia a una clase

In [ ]:
# Selección de modelo:
# 1. train/test en 1 base: (métrica única, overfit malo, low accuracy may indicate implementation code error)
# 2. single train,test split produce únicas métricas de evaluación ( single metric, lack of variance, not good picture of future predictions)
# 3. k-fold cross-validations para dividir la base en k-fold, then promediar las métricas evaluación. (más estable)

# scoring = 'evaluation_metric' ,  crear  cross-val  para una métrica de evaluación especifica a optimizar 
# cross_val_score(clf, X, y, cv=5, scoring = eval_metric)
# generar  cross-val score para modelo con diferentes métricas de evaluación 


# GridSearchCV(model, param_grid = parameter_range), encontrar los hiper parámetros óptimos para el modelo fit/train ajustado dada una base
# para optimizar una métrica evaluación dada 

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC

# load source data
dataset = load_digits()
# again, making this a binary problem with 'digit 1' as positive class 
# and 'not 1' as negative class
X, y = dataset.data, dataset.target == 1

# create SVectorMachine Linear, parameters: kernel='linear', C=1
clf = SVC(kernel='linear', C=1)

# generate cross-val score for model with different evaluation metrics

# accuracy is the default scoring metric
print('Cross-validation (accuracy)', cross_val_score(clf, X, y, cv=5 )  )
print('Average cross-validation, evaluation metric= Accuracy:', np.average(cross_val_score(clf, X, y, cv=5) ))
print('\b')
# use AUC as scoring metric
print('Cross-validation (AUC)', cross_val_score(clf, X, y, cv=5, scoring = 'roc_auc'))
print('Average cross-validation, evaluation metric= AUC:', np.average(cross_val_score(clf, X, y, cv=5, scoring = 'roc_auc') ))
print('\b')
# use recall as scoring metric
print('Cross-validation (recall)', cross_val_score(clf, X, y, cv=5, scoring = 'recall'))
print('Average cross-validation, evaluation metric= recall:', np.average(cross_val_score(clf, X, y, cv=5, scoring = 'recall') ))
print('\b')

In [ ]:
# GridSearch

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score

# load source data
dataset = load_digits()

# create unbalanced 0-1 binary class dataset
X, y = dataset.data, dataset.target == 1

# divide source data into train-set and test-set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# create SVectorMachine RBF, parameters: kernel='rbf'
clf = SVC(kernel='rbf')

# gamma parameter range to search over
grid_values = {'gamma': [0.001, 0.01, 0.05, 0.1, 1, 10, 100]}


# default metric to optimize over grid parameters: accuracy

# GridSearchCV(clf, param_grid = grid_values), 
#find the value of parameter that optimizes a given evaluation metric   over its range
grid_clf_acc = GridSearchCV(clf, param_grid = grid_values, scoring = 'accuracy')
grid_clf_acc.fit(X_train, y_train)

# optimize model for evaluation metric average accuracy
y_decision_fn_scores_acc = grid_clf_acc.decision_function(X_test) 

print('Grid best parameter (max. accuracy): ', grid_clf_acc.best_params_)
print('Grid best score (accuracy): ', grid_clf_acc.best_score_)



# alternative metric to optimize over grid parameters: AUC

# GridSearchCV(clf, param_grid = grid_values), find the value of parameter
# that optimizes a given evaluation metric 
grid_clf_auc = GridSearchCV(clf, param_grid = grid_values, scoring = 'roc_auc')
grid_clf_auc.fit(X_train, y_train)
# optimize model for evaluation metric AUC
y_decision_fn_scores_auc = grid_clf_auc.decision_function(X_test) 


print('Test set AUC: ', roc_auc_score(y_test, y_decision_fn_scores_auc))
print('Grid best parameter (max. AUC): ', grid_clf_auc.best_params_)
print('Grid best score (AUC): ', grid_clf_auc.best_score_)


# crear SupportVectorMachine optimo
svm =  SVC(kernel='rbf',gamma=0.001).fit(X_train,y_train)


# crear vector de predicciones y_hat

y_hat_train = svm.predict(X_train)
y_hat_test = svm.predict(X_test)


# matriz de confusion
confusion_train = confusion_matrix(y_train, y_hat_train)
confusion_test = confusion_matrix(y_test, y_hat_test)

# metricas de evaluacion

train_acc = accuracy_score(y_train, y_hat_train )
test_acc = accuracy_score(y_test, y_hat_test )

train_prec =precision_score(y_train, y_hat_train)
test_prec =precision_score(y_test, y_hat_test )

train_recall = recall_score(y_train, y_hat_train )
test_recall = recall_score(y_test, y_hat_test )

train_f1 = f1_score(y_train, y_hat_train )
test_f1 = f1_score(y_test, y_hat_test )
















print('Test set AUC: ', roc_auc_score(y_test, y_decision_fn_scores_auc))
print('Grid best parameter (max. AUC): ', grid_clf_auc.best_params_)
print('Grid best score (AUC): ', grid_clf_auc.best_score_)




svm

In [ ]:
from sklearn.metrics.scorer import SCORERS

print(sorted(list(SCORERS.keys())))

In [ ]:
# different evaluation metrics

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from adspy_shared_utilities import plot_class_regions_for_classifier_subplot
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

# load data 
dataset = load_digits()
X, y = dataset.data, dataset.target == 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# Create a two-feature input vector matching the example plot above
# We jitter the points (add a small amount of random noise) in case there are areas
# in feature space where many instances have the same features.

# use GridSearh to explore different weigths given during training
# 


jitter_delta = 0.25
X_twovar_train = X_train[:,[20,59]]+ np.random.rand(X_train.shape[0], 2) - jitter_delta
X_twovar_test  = X_test[:,[20,59]] + np.random.rand(X_test.shape[0], 2) - jitter_delta

# create SVector Machine Linear, parameters: kernel = linear, fit/train with train-set
clf = SVC(kernel = 'linear').fit(X_twovar_train, y_train)

# class weight parameter of weight
grid_values = {'class_weight':['balanced', {1:2},{1:3},{1:4},{1:5},{1:10},{1:20},{1:50}]}
plt.figure(figsize=(9,6))

# iterate over evaluation metrics
for i, eval_metric in enumerate(('precision','recall', 'f1','roc_auc')):
    
    #find the value of parameter that optimizes a given evaluation metric 
    grid_clf_custom = GridSearchCV(clf, param_grid=grid_values, scoring=eval_metric)
    grid_clf_custom.fit(X_twovar_train, y_train)
    
    # get best parameter for score
    print('Grid best parameter (max. {0}): {1}'
          .format(eval_metric, grid_clf_custom.best_params_))
    # get best score/performance metric
    print('Grid best score ({0}): {1}'
          .format(eval_metric, grid_clf_custom.best_score_))
    plt.subplots_adjust(wspace=0.3, hspace=0.3)
    plot_class_regions_for_classifier_subplot(grid_clf_custom, X_twovar_test, y_test, None,
                                             None, None,  plt.subplot(2, 2, i+1))
    
    plt.title(eval_metric+'-oriented SVC')
plt.tight_layout()
plt.show()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve
from adspy_shared_utilities import plot_class_regions_for_classifier
from sklearn.svm import SVC

dataset = load_digits()
X, y = dataset.data, dataset.target == 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# create a two-feature input vector matching the example plot above
jitter_delta = 0.25
X_twovar_train = X_train[:,[20,59]]+ np.random.rand(X_train.shape[0], 2) - jitter_delta
X_twovar_test  = X_test[:,[20,59]] + np.random.rand(X_test.shape[0], 2) - jitter_delta

clf = SVC(kernel='linear', class_weight='balanced').fit(X_twovar_train, y_train)

y_scores = clf.decision_function(X_twovar_test)

precision, recall, thresholds = precision_recall_curve(y_test, y_scores)
closest_zero = np.argmin(np.abs(thresholds))
closest_zero_p = precision[closest_zero]
closest_zero_r = recall[closest_zero]

plot_class_regions_for_classifier(clf, X_twovar_test, y_test)
plt.title("SVC, class_weight = 'balanced', optimized for accuracy")
plt.show()

plt.figure()
plt.xlim([0.0, 1.01])
plt.ylim([0.0, 1.01])
plt.title ("Precision-recall curve: SVC, class_weight = 'balanced'")
plt.plot(precision, recall, label = 'Precision-Recall Curve')
plt.plot(closest_zero_p, closest_zero_r, 'o', markersize=12, fillstyle='none', c='r', mew=3)
plt.xlabel('Precision', fontsize=16)
plt.ylabel('Recall', fontsize=16)
plt.axes().set_aspect('equal')
plt.show()
print('At zero threshold, precision: {:.2f}, recall: {:.2f}'
      .format(closest_zero_p, closest_zero_r))