# Pandas

# Librerias

In [3]:
# general
import numpy as np
import re
import pandas as pd
import os
import timeit


# visualización
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use('seaborn-colorblind')
#from data_exploration import explore


C:\Users\Diego\AppData\Local\Temp\ipykernel_10472\648857513.py:13: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-colorblind')


# List comprehension: for simplificado

obj= [action for x in obj]

# Numpy 


## Numpy estructuras de datos

In [13]:
# Numpy 
# crear array
a = np.array([[1,2], [3, 4], [5, 6]])
# array extrayendo elementos de otro array
b = np.array([a[0, 0], a[1, 1], a[2, 1]])
# crear array, especificar tipo de estructura de dato
np.array([1, 2, 3, 4], dtype=np.float32)



array([1., 2., 3., 4.], dtype=float32)

In [14]:
# forma de array
shape1 = a.shape 

# tipo de items en array
type1 = a.dtype

# nombre de tipo de array
type_name1 = a.dtype.name

In [15]:
# crear array de 1s  3x5
ones = np.ones((3, 5), dtype=float)

# crear array de 0s 1x10
zeros=np.zeros(10, dtype=int)

# crear full array de valor fijo 3.14
full = np.full((3, 5), 3.14)
full

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

## Numpy arange

In [16]:
# crear array en secuencia lineal
# start=0, end= 20, step=2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# crear array de valores separados igual
# start=0, stop= 1, num=2
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# crear array 3x3 distribucion uniforme random 
# pseudorandom values between 0 and 1
rand1 = np.random.random((3, 3))

# crear array 3x3 distribucion normal random
# values with mean 0 and standard deviation 1
# u=0,lamda=1
np.random.normal(0, 1, (3, 3))


array([[ 0.60895269,  0.97087613,  0.1947929 ],
       [-0.74179926,  0.93259533,  0.71334773],
       [ 0.66445643,  0.99096237,  0.76056889]])

In [19]:
# crear 3x3 matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Index y mascara bool
aplu5 = a>5
print(aplu5)
# 
map_aplu5=a[a>5]
print(map_aplu5)

[[False False]
 [False False]
 [False  True]]
[6]


## Indexing

Obtener elementos de objetos

In [21]:
a = np.array([1,3,5,7])
a

array([1, 3, 5, 7])

In [22]:

a[2]

5

In [23]:
# For multidimensional array, we need to use integer array indexing, let's create a new multidimensional array
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
a[1,1] # remember in python we start at 0!

4

In [25]:
# if we want to get multiple elements 
# for example, 1, 4, and 6 and put them into a one-dimensional array
# we can enter the indices directly into an array function
np.array([a[0, 0], a[1, 1], a[2, 1]])

array([1, 4, 6])

In [26]:
# second list up
print(a[[0, 1, 2], [0, 1, 1]])

[1 4 6]


## Indexing Booleano

Obtener elementos de array por condicion

In [27]:
# This returns a boolean array showing that if the value at the corresponding index is greater than 5
print(a >5)

[[False False]
 [False False]
 [False  True]]


In [28]:
# array relating to the true values.
print(a[a>5])

[6]


## Slicing

Crear sub-arrays a partir del original

In [29]:
# Slicing
a = np.array([0,1,2,3,4,5])
a_03 = a[:4]
a_24 = a[2:4]

print(a_03)
print(a_24)

[0 1 2 3]
[2 3]


In [30]:
# brackets, we get elements from index 0 to index 3 (excluding index 3)
a = np.array([0,1,2,3,4,5])
print(a[:3])

[0 1 2]


In [31]:
# array multi-dimension
# array_n = np.array([ [],[],[]  ])
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print("")

# a_02 primeros 2 arrays dentro de n-array
a_02 = a[:2]
print(a_02)
print("")

a_02_13 = a[:2,1:3]
a_02_13
print(a_02_13)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3 4]
 [5 6 7 8]]

[[2 3]
 [6 7]]


In [32]:
# los multi- arrays el primer argumento es para seleccionra filas
# el segundo argumento es para seleccionra columnas

In [33]:
# Here I'll change the element at position [0, 0], which is 2, to 50, then we can see that the value in the
# original array is changed to 50 as well

sub_array = a[:2, 1:3]
print("sub array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 50
print("sub array index [0,0] value after change:", sub_array[0,0])
print("original array index [0,1] value after change:", a[0,1])

sub array index [0,0] value before change: 2
sub array index [0,0] value after change: 50
original array index [0,1] value after change: 50


In [34]:
# Operaciones con arrays on aplicando elementwise.
# crear arrays
a = np.array([10,20,30,40])
b = np.array([1, 2, 3,4])

# restar arrays 
c = a-b
print(c)

# multiplicar arrays
d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [35]:
# crear arrays
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
# producto elementwise
C = A*B
print(A*B)

# producto punto (producto matricial)
C2=A@B
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [36]:
# dimensiones de array
A.shape

(2, 2)

In [37]:
# concatenar listas
[1,2] + [3,2]


[1, 2, 3, 2]

In [38]:
# verificar si elemento esta en lista 
1 in [1,2,3,4]

True

## Operaciones con arrays

In [39]:
# crera arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1)

# crear array de flotas
array2 = np.array([[7.1, 8.2, 9.1], [10.4, 11.2, 12.3]])
print(array2)

# sumar arrays
array3=array1+array2
print(array3)

[[1 2 3]
 [4 5 6]]
[[ 7.1  8.2  9.1]
 [10.4 11.2 12.3]]
[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]


In [40]:
# funciones sum,max,min,mean(avg)
print("sumar elementos",array3.sum())
print("maximo de elementos en array",array3.max())
print("minimo de elementos en array",array3.min())
print("promedio de array",array3.mean())

sumar elementos 79.3
maximo de elementos en array 18.3
minimo de elementos en array 8.1
promedio de array 13.216666666666667


In [41]:
# Arithmetic operators on array apply elementwise.

# Let's create a couple of arrays
a = np.array([10,20,30,40])
b = np.array([1, 2, 3,4])

# Now let's look at a minus b
c = a-b
print(c)

# And let's look at a times b
d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [42]:
# Let's create an array of typical Ann Arbor winter farenheit values
farenheit = np.array([0,-10,-5,-15,0])

# And the formula for conversion is ((°F − 32) × 5/9 = °C)
celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [43]:
# modulus operator para ver numeros pares divisibles por  2
celcius%2 == 0

array([False, False,  True, False, False])

In [44]:
# Let's create an array of integers
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1.dtype)

# Now let's create an array of floats
array2 = np.array([[7.1, 8.2, 9.1], [10.4, 11.2, 12.3]])
print(array2.dtype)

# Let's do an addition for the two arrays
array3=array1+array2
print(array3)
print(array3.dtype)

int32
float64
[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


## Funciones de agregación

In [45]:
# funciones de agregación
print(array3.sum()) # suma 
print(array3.max()) # máximo
print(array3.min()) # mínimo
print(array3.mean()) # promedio

79.3
18.3
8.1
13.216666666666667


In [46]:
# For two dimensional arrays, we can do the same thing for each row or column
# let's create an array with 15 elements, ranging from 1 to 15, 
# with a dimension of 3X5
b = np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


## Diccionarios

{key:value}

In [47]:
# los diccionarios son listas que asocian keys con valores  'key': 'value'
# dic= {'key-n','value-n'}
dic1 = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
dic1['Christopher Brooks'] # obtener valor de un key 


'brooksch@umich.edu'

In [48]:
dic1['Kevyn Collins-Thompson'] = None
dic1['Kevyn Collins-Thompson']
dic1

{'Christopher Brooks': 'brooksch@umich.edu',
 'Bill Gates': 'billg@microsoft.com',
 'Kevyn Collins-Thompson': None}

In [49]:
# iterar sobre keys de diccionario
for key in dic1.keys():
    print(key)

Christopher Brooks
Bill Gates
Kevyn Collins-Thompson


In [50]:
# iterar sobre valores de diccionario
for value in dic1.values():
    print(value)

brooksch@umich.edu
billg@microsoft.com
None


In [51]:
# iterar sobre items de la lista

for key,value in dic1.items():
    print('key:',key)
    print('value:',value)
    print("")

key: Christopher Brooks
value: brooksch@umich.edu

key: Bill Gates
value: billg@microsoft.com

key: Kevyn Collins-Thompson
value: None



## Numpy Datasets

In [52]:
# cargar base de vinos
wines = np.genfromtxt("data/winequality-red.csv", delimiter=";", skip_header=1)
wines


array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [53]:
wines_rows_0column1 = wines[:,0] # todas las filas, primera columna
wines_rows_0column2 = wines[:, 0:1] # todas las filas, primera columna(mantiene forma)
wines_rows_0column3 = wines[:,0:3] # todas las filas, columnas 0-2 (no incluye 3)
wines_rows_columns024 = wines[:,[0,2,4] ] # todas las filas, columnas 0,2,4

print(wines_rows_0column1)
print("")
print(wines_rows_0column2)
print("")
print(wines_rows_0column3)
print("")
print(wines_rows_columns024)



[7.4 7.8 7.8 ... 6.3 5.9 6. ]

[[7.4]
 [7.8]
 [7.8]
 ...
 [6.3]
 [5.9]
 [6. ]]

[[7.4   0.7   0.   ]
 [7.8   0.88  0.   ]
 [7.8   0.76  0.04 ]
 ...
 [6.3   0.51  0.13 ]
 [5.9   0.645 0.12 ]
 [6.    0.31  0.47 ]]

[[7.4   0.    0.076]
 [7.8   0.    0.098]
 [7.8   0.04  0.092]
 ...
 [6.3   0.13  0.076]
 [5.9   0.12  0.075]
 [6.    0.47  0.067]]


In [54]:
wines[:,-1] # todas las filas, última columna
prom1 = wines[:,-1].mean() # promedio de última columna
prom1

5.6360225140712945

In [55]:
# cargar base admission Dataset
graduate_admission = np.genfromtxt('data/Admission_Predict.csv', dtype=None, delimiter=',', skip_header=1,
                                   names=('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'))
graduate_admission

array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [56]:
graduate_admission.shape # array con 400 tuplas

(400,)

In [57]:
# Slicing por columna
columnCGPA_rows05 =graduate_admission['CGPA'][0:5] # filas 0-4 de la columna ['CGPA']
print('columna columnCGPA, filas 0-5',columnCGPA_rows05)

# transformar columna CGPA a escala 5
graduate_admission['CGPA'] = graduate_admission['CGPA']/10 *4 # multiplicar columna 'CGPA' *(4/10)
print('columna CGPA transformada escala 5',graduate_admission)
columnCGPA_rows020 = graduate_admission['CGPA'][0:20]# filas 0-19 de la columna ['CGPA']
print('columna columnCGPA, filas 0-20',columnCGPA_rows020)

graduate_admission['CGPA']

columna columnCGPA, filas 0-5 [9.65 8.87 8.   8.67 8.21]
columna CGPA transformada escala 5 [(  1, 337, 118, 4, 4.5, 4.5, 3.86 , 1, 0.92)
 (  2, 324, 107, 4, 4. , 4.5, 3.548, 1, 0.76)
 (  3, 316, 104, 3, 3. , 3.5, 3.2  , 1, 0.72)
 (  4, 322, 110, 3, 3.5, 2.5, 3.468, 1, 0.8 )
 (  5, 314, 103, 2, 2. , 3. , 3.284, 0, 0.65)
 (  6, 330, 115, 5, 4.5, 3. , 3.736, 1, 0.9 )
 (  7, 321, 109, 3, 3. , 4. , 3.28 , 1, 0.75)
 (  8, 308, 101, 2, 3. , 4. , 3.16 , 0, 0.68)
 (  9, 302, 102, 1, 2. , 1.5, 3.2  , 0, 0.5 )
 ( 10, 323, 108, 3, 3.5, 3. , 3.44 , 0, 0.45)
 ( 11, 325, 106, 3, 3.5, 4. , 3.36 , 1, 0.52)
 ( 12, 327, 111, 4, 4. , 4.5, 3.6  , 1, 0.84)
 ( 13, 328, 112, 4, 4. , 4.5, 3.64 , 1, 0.78)
 ( 14, 307, 109, 3, 4. , 3. , 3.2  , 1, 0.62)
 ( 15, 311, 104, 3, 3.5, 2. , 3.28 , 1, 0.61)
 ( 16, 314, 105, 3, 3.5, 2.5, 3.32 , 0, 0.54)
 ( 17, 317, 107, 3, 4. , 3. , 3.48 , 0, 0.66)
 ( 18, 319, 106, 3, 4. , 3. , 3.2  , 1, 0.65)
 ( 19, 318, 110, 3, 4. , 3. , 3.52 , 0, 0.63)
 ( 20, 303, 102, 3, 3.5, 3. , 3.4 

array([3.86 , 3.548, 3.2  , 3.468, 3.284, 3.736, 3.28 , 3.16 , 3.2  ,
       3.44 , 3.36 , 3.6  , 3.64 , 3.2  , 3.28 , 3.32 , 3.48 , 3.2  ,
       3.52 , 3.4  , 3.16 , 3.36 , 3.8  , 3.88 , 3.92 , 3.84 , 3.52 ,
       3.   , 2.88 , 2.92 , 3.24 , 3.32 , 3.76 , 3.84 , 3.92 , 3.68 ,
       3.36 , 3.12 , 3.   , 3.08 , 3.2  , 3.28 , 3.4  , 3.64 , 3.76 ,
       3.64 , 3.72 , 3.88 , 3.54 , 3.36 , 3.32 , 3.16 , 3.2  , 3.24 ,
       3.2  , 3.08 , 2.96 , 3.04 , 2.72 , 3.32 , 3.24 , 3.28 , 3.28 ,
       3.4  , 3.48 , 3.568, 3.608, 3.456, 3.688, 3.664, 3.856, 3.904,
       3.78 , 3.616, 3.56 , 3.424, 3.488, 3.288, 3.016, 2.944, 3.208,
       3.8  , 3.688, 3.744, 3.78 , 3.464, 3.368, 3.312, 3.256, 3.504,
       3.168, 3.064, 3.212, 3.152, 3.064, 3.136, 3.2  , 3.584, 3.696,
       3.552, 3.384, 3.248, 3.3  , 3.388, 3.62 , 3.512, 3.672, 3.784,
       3.752, 3.456, 3.392, 3.472, 3.336, 3.424, 3.38 , 3.616, 3.448,
       2.984, 2.912, 3.536, 3.824, 3.792, 3.344, 3.288, 3.388, 3.464,
       3.728, 3.484,

## Transformar base de datos por condición (boolean)

In [58]:
# filas por condicion (boolena)
columnaResearch_cond1 = graduate_admission[graduate_admission['Research']==1]
print(len(graduate_admission[graduate_admission['Research'] == 1]))
columnaResearch_cond1


219


array([(  1, 337, 118, 4, 4.5, 4.5, 3.86 , 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 3.548, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 3.2  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 3.468, 1, 0.8 ),
       (  6, 330, 115, 5, 4.5, 3. , 3.736, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 3.28 , 1, 0.75),
       ( 11, 325, 106, 3, 3.5, 4. , 3.36 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 3.6  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 3.64 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 3.2  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 3.28 , 1, 0.61),
       ( 18, 319, 106, 3, 4. , 3. , 3.2  , 1, 0.65),
       ( 21, 312, 107, 3, 3. , 2. , 3.16 , 1, 0.64),
       ( 23, 328, 116, 5, 5. , 5. , 3.8  , 1, 0.94),
       ( 24, 334, 119, 5, 5. , 4.5, 3.88 , 1, 0.95),
       ( 25, 336, 119, 5, 4. , 3.5, 3.92 , 1, 0.97),
       ( 26, 340, 120, 5, 4.5, 4.5, 3.84 , 1, 0.94),
       ( 28, 298,  98, 2, 1.5, 2.5, 3.   , 1, 0.44),
       ( 31, 300,  97, 2, 3. , 3. , 3.24 , 1, 

In [59]:
# Transformar base por condicion
# filas por condición columna 'Chance_of_Admit']>0.8, sacar promedio de columna 'CGPA'
trans_condChance_of_Admitplus08_columnCGPA = graduate_admission[graduate_admission['Chance_of_Admit']>0.8]['CGPA'].mean()

# filas por condición 'Chance_of_Admit']<0.4, sacar promedio de columna 'CGPA'
trans_condChance_of_Admitless04_columnCGPA  = graduate_admission[graduate_admission['Chance_of_Admit']<0.4]['CGPA'].mean()
print('Promedio CGPA observaciones con Chance_of_Admit > 0.8',trans_condChance_of_Admitplus08_columnCGPA)
print('Promedio CGPA observaciones con Chance_of_Admit < 0.4',trans_condChance_of_Admitless04_columnCGPA)

Promedio CGPA observaciones con Chance_of_Admit > 0.8 3.7106666666666666
Promedio CGPA observaciones con Chance_of_Admit < 0.4 3.0222857142857142


In [60]:
# transformaciones
# filas por condición columna 'Chance_of_Admit']>0.8, sacar promedio de columna 'GRE'
trans_condChance_of_Admitplus08_columnGRE_ScoreProm = graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['GRE_Score'].mean()
# filas por condición columna 'Chance_of_Admit']<0.4, sacar promedio de columna 'GRE'
trans_condChance_of_Admitless04_columnGRE_ScoreProm = graduate_admission[graduate_admission['Chance_of_Admit'] < 0.4]['GRE_Score'].mean()

print(graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['GRE_Score'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit'] < 0.4]['GRE_Score'].mean())

328.7350427350427
302.2857142857143


## Reshaping

In [61]:
# crear array 1-9
grid = np.arange(1, 10)
print('original 1x9: ',grid)
print("")
# cambiar formato de array nxm
reshape= grid.reshape(3, 3)
print('reshape 3x3: ',reshape)

original 1x9:  [1 2 3 4 5 6 7 8 9]

reshape 3x3:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
# crear array
x = np.array([1, 2, 3])
# cambiar formato
x.reshape((1, 3)) 


array([[1, 2, 3]])

In [63]:
x.reshape((3, 1)) 

array([[1],
       [2],
       [3]])

In [64]:
# crear arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
# concatenar arrays x+y
conc = np.concatenate([x, y])
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]),conc)

[ 1  2  3  3  2  1 99 99 99] [1 2 3 3 2 1]


## Strings

In [65]:
# crear diccionario sales_record
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

# crear formato de string
sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

# print   estructura.format(formato['key-n'])  
print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


## Fechas y Tiempo

In [66]:
import datetime as dt
import time as tm

In [67]:
tm.time() # tiempo transcurrido desde Epoch

1692489669.8237503

In [68]:
# convertir objeto timestamp y datetime
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2023, 8, 19, 19, 1, 9, 844505)

In [69]:
# atributos de clase datetime
# año, mes, dia, hora, minuto ,segundo 
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second


(2023, 8, 19, 19, 1, 9)

In [70]:
# delta de tiempo de 100 dias
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(days=100)

In [71]:
# fecha hoy
today = dt.date.today()
today

datetime.date(2023, 8, 19)

In [72]:
# fecha de hoy - delta tiempo
today - delta 

datetime.date(2023, 5, 11)

## Función Lambda

In [73]:
funcion_lambda = lambda a, b, c : a + b
funcion_lambda(2,2,1)

4

In [74]:
# iterar sobre lista con for loop
lista = []
for num in range(0, 1000):
    if num % 2 == 0: # num es divisible por 2
        lista.append(num)
print(lista)

# iterar sobre lista con list comprehension
lista2 = []
lista2 = [num for num in range(0,1000) if num % 2 == 0]
print(lista2)

lista==lista2


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420,

True

# Regex

In [75]:
# importar libreria regex
import re


In [76]:
# crear texto
text = "This is a good day."

# buscar patron en texto
# re.search("patron", texto)
if re.search("good", text): 
    print("Wonderful!")
else:
    print("Alas :(")

Wonderful!


In [77]:
# crear texto
text = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."

# split texto en lista, a partir de patron
# re.split(texto,patron) 
re.split("Amy", text)

['',
 ' works diligently. ',
 ' gets good grades. Our student ',
 ' is succesful.']

In [78]:
# contar cuantas veces hay patron en texto
# re.findall(patron, texto)
re.findall("Amy", text)



['Amy', 'Amy', 'Amy']

In [79]:
# crear texto
text = "Amy works diligently. Amy gets good grades. Our student Amy is succesful."

# condicion texto empieza con patron
# re.search("^patron", texto)
re.search("^Amy",text)

<re.Match object; span=(0, 3), match='Amy'>

## Patrones y Caracteres

In [80]:
# texto
grades="ACAAAABCBCBAA"

# contar veces de caracter en texto
# re.findall("char",texot)
re.findall("B",grades)

['B', 'B', 'B']

In [81]:
# contar veces de varios caracteres 
# re.findall("[char1char2charn]",texto)
print(re.findall("[AB]",grades) )
print(len(re.findall("[AB]",grades)))

['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A']
10


In [82]:
# contar veces caracter1, seguido de caracter2 o caracter2
# re.findall("[char1][char2-char3]", texto)

print(re.findall("[A][B-C]",grades) )
print(re.findall("AB|AC",grades))

['AC', 'AB']
['AC', 'AB']


In [83]:
# lista de caracteres excepto patron
# re.findall("[^patron]",texto)
re.findall("[^A]",grades)

['C', 'B', 'C', 'B', 'C', 'B']

## Quantifiers "patron{min,max}"


In [84]:
# contar veces de caracter en secuencia con cuantificador
# re.findall("char{min,max}",texto)
re.findall("A{2,10}",grades) 

['AAAA', 'AA']

In [85]:
# si no se incluye el cuantificador en el regex se asume min=max=1
re.findall("AA",grades)

['AA', 'AA', 'AA']

In [86]:
# cuantificador con solo parametro es {min=max=n}
re.findall("A{2}",grades)

['AA', 'AA', 'AA']

## Cuantificadores
 {min,max}
 *: match 0 o más elementos
 ?: match 1 o más elementos
 +: match 1 o más elementos
 [a-zA-Z]: cualquier palabra
 [\w]: cualquier palabra y numero (alfanumerico)



In [87]:
with open("data/ferpa.txt","r") as file:
    # we'll read that into a variable called wiki
        wiki=file.read()
    # and lets print that variable out to the screen
wiki

'Overview[edit]\nFERPA gives parents access to their child\'s education records, an opportunity to seek to have the records amended, and some control over the disclosure of information from the records. With several exceptions, schools must have a student\'s consent prior to the disclosure of education records after that student is 18 years old. The law applies only to educational agencies and institutions that receive funds under a program administered by the U.S. Department of Education.\n\nOther regulations under this act, effective starting January 3, 2012, allow for greater disclosures of personal and directory student identifying information and regulate student IDs and e-mail addresses.[2] For example, schools may provide external companies with a student\'s personally identifiable information without the student\'s consent.[2]\n\nExamples of situations affected by FERPA include school employees divulging information to anyone other than the student about the student\'s grades o

In [88]:
# encontrar cualquier palabra, entre 1 y 100 letras, seguido de patron \[edit\] 
re.findall("[a-zA-Z]{1,100}\[edit\]",wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [89]:
# encontrar cualquier palabra alfanumerica, entre 1 y 100 caracteres, seguido de patron \[edit\]
re.findall("[\w]{1,100}\[edit\]",wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [90]:
# encontrar cualquier palabra alfanumerica, entre 0 y más caracteres, seguido de patron \[edit\]
re.findall("[\w]*\[edit\]",wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [91]:
# encontrar cualquier palabra alfanumerica + espacio, entre 0 y más caracteres, seguido de patron \[edit\]
re.findall("[\w ]*\[edit\]",wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [92]:
# iterar sobre titulos en regex
# regex: encontrar cualquier palabra alfanumerica + espacio, entre 0 y más caracteres, seguido de patron \[edit\]
for title in re.findall("[\w ]*\[edit\]",wiki):
    # split titulo de cada regex con patron [\[]
    # tomar primer elemento
    print(re.split("[\[]",title)[0])

Overview
Access to public records
Student medical records


## Grupos de regex

In [93]:
# encontrar varios regex/grupos de regex
# re.findall("(patron1)(patron2)")
re.findall("([\w ]*)(\[edit\])",wiki)

[('Overview', '[edit]'),
 ('Access to public records', '[edit]'),
 ('Student medical records', '[edit]')]

In [94]:
# re.finditer("(patron1)(patron2)") lista de matchs

# regex=  (cualquier palabra + espacio)(\[edit\])
# iterar sobre lista de match
for item in re.finditer("([\w ]*)(\[edit\])",wiki):
    print(item.groups())
    

('Overview', '[edit]')
('Access to public records', '[edit]')
('Student medical records', '[edit]')


In [95]:
print(item.groupdict())


{}


In [96]:

# # match 2 grupos
# # primer grupo es title
# # segundo grupo es [edit]
# for item in re.finditer("(?P<title>[\w ]+)(?=\[edit\])",wiki):
#     # What this regex says is match two groups, the first will be named and called title, will have any amount
#     # of whitespace or regular word characters, the second will be the characters [edit] but we don't actually
#     # want this edit put in our output match objects
#     print(item)

In [8]:
# # We can see that each university follows a fairly similar pattern, with the name followed by an – then the
# # words "located in" followed by the city and state

# # I'll actually use this example to show you the verbose mode of python regexes. The verbose mode allows you
# # to write multi-line regexes and increases readability. For this mode, we have to explicitly indicate all
# # whitespace characters, either by prepending them with a \ or by using the \s special value. However, this
# # means we can write our regex a bit more like code, and can even include comments with #
# pattern="""
# (?P<title>.*)        #the university title
# (–\ located\ in\ )   #an indicator of the location
# (?P<city>\w*)        #city the university is in
# (,\ )                #separator for the state
# (?P<state>\w*)       #the state the city is located in"""

# # Now when we call finditer() we just pass the re.VERBOSE flag as the last parameter, this makes it much
# # easier to understand large regexes!
# for item in re.finditer(pattern,wiki,re.VERBOSE):
#     # We can get the dictionary returned for the item with .groupdict()
#     print(item.groupdict())

## New York Times y Hashtags

In [ ]:
# with open("data/nytimeshealth.txt","r") as file:
#     # We'll read everything into a variable and take a look at it
#     health=file.read()
# health

In [9]:
# # So lets create a pattern. We want to include the hash sign first, then any number of alphanumeric
# # characters. And we end when we see some whitespace
# pattern = '#[\w\d]*(?=\s)'

# # Notice that the ending is a look ahead. We're not actually interested in matching whitespace in the return
# # value. Also notice that I use an asterix * instead of the plus + for the matching of alphabetical characters
# # or digits, because a + would require at least one of each

# # Lets searchg and display all of the hashtags
# re.findall(pattern, health)

# DataFrames

## Series

Array 1D de pandas de data con indices asociados a las posiciones 

In [377]:
# crear Serie de pandas
serie1 = pd.Series([0.25, 0.5, 0.75, 1.0])
serie1

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [378]:
# valores de la Serie
serie1.values

array([0.25, 0.5 , 0.75, 1.  ])

In [379]:
# index de Serie
serie1.index

RangeIndex(start=0, stop=4, step=1)

In [380]:
# crear Serie de Pandas
data1 = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data1['b']

0.5

In [381]:
# crear Serie con indices no secuenciales
data2 = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data2

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [382]:
# crear Serie como dict  {'key':'vaue'}
population_dict = {'California': 39538223, 'Texas': 29145505,
                   'Florida': 21538187, 'New York': 20201249,
                   'Pennsylvania': 13002700}
population = pd.Series(population_dict)
population

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
dtype: int64

In [383]:
# operaciones de slicing de arrays
population['California':'Florida']

California    39538223
Texas         29145505
Florida       21538187
dtype: int64

In [384]:
ser1 = pd.Series([2, 4, 6])
ser2 = pd.Series(5, index=[100, 200, 300])
ser2

100    5
200    5
300    5
dtype: int64

In [385]:
ser3 = pd.Series({2:'a', 1:'b', 3:'c'})
ser3

2    a
1    b
3    c
dtype: object

## DataFrames 

In [97]:
# crear Serie de Estados como dict {'key':val}
area_dict = {'California': 423967, 'Texas': 695662, 'Florida': 170312, 
             'New York': 141297, 'Pennsylvania': 119280}
area = pd.Series(area_dict)
area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
dtype: int64

In [388]:
# crear DataFrame como dict  
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

In [389]:
# seleccionar columna 'population'
states['population'] # seleccionar por nombre de columna

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Name: population, dtype: int64

In [390]:
states.loc[:,'population'] # seleccionar por slicing


California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Name: population, dtype: int64

In [391]:
states.population # seleccionar por columna

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Name: population, dtype: int64

In [392]:
states.iloc[:,0] # seleccionar por indice

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Name: population, dtype: int64

In [393]:
# slicing por filas 
states.iloc[0,:]

population    39538223
area            423967
Name: California, dtype: int64

In [394]:
# slicing por columnas
states.iloc[:,0]

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
Name: population, dtype: int64

In [395]:
# slicing filas
states.iloc[2:4,:]

population    area
Florida     21538187  170312
New York    20201249  141297

In [396]:
# indice de DataFrame 
states.index

Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania'], dtype='object')

In [397]:
# columnas de DataFrame
states.columns

Index(['population', 'area'], dtype='object')

## Construir objetos DataFrame 

In [398]:
# construir DataFrame de 1 Serie 
pd.DataFrame(population, columns=['population'])

population
California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700

In [399]:
# construir DataFrame de lista de dict
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [400]:
# NAN = Not A  Number
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [401]:
# construir DataFrame de lista de dict de Series
pd.DataFrame({'population': population,
              'area': area})

population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

In [402]:
# construir DataFrame de numpy array 2D
# definir nombre de columnas
# definir indice
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.794299  0.915694
b  0.484209  0.433148
c  0.482931  0.101635

In [403]:
# construir DataFrame de array estructurado
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
pd.DataFrame(A)


A    B
0  0  0.0
1  0  0.0
2  0  0.0

## Objeto Index 

Array inmutable - set ordenado 

In [404]:
# crear objeto Index
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [405]:
ind[1]

3

In [406]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [407]:
# crear Index
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indB

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [408]:
# interseccion entre indices
# indA n indB
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [409]:
# union entre indices
# indA u indB
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [410]:
indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

In [411]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [412]:
# crear Series como lista de float, index 
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [413]:
# acceder a Serie por index
data['b']

0.5

In [414]:
# usar expresiones de dict para ver keys/indices y valores
'a' in data


True

In [415]:
# keys de Serie como dict
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [416]:
# lista de tuplas (key,value) en Serie como dict
list(data.items())
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [417]:
# crear tupla key-value
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [418]:
# slicing por indices
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [419]:
# slicing por numero de indice
data[0:2]
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [420]:
# masking: mascara sobre Serie por condicion
data[(data > 0.3) & (data < 0.8)]


b    0.50
c    0.75
dtype: float64

In [421]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [422]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [423]:
# indexing por numero
data[1]

'a'

In [424]:
# indexing al hacer slicing
data[1:3]
data

1    a
3    b
5    c
dtype: object

In [425]:
# loc atributo que hacer indexing y slicing a indice numerico
# obtener valor de indice
data.loc[1]

'a'

In [426]:
# loc  indexing y slicing con indice por numero
data.loc[1:3]

1    a
3    b
dtype: object

In [427]:
# iloc  indexing y slicing con indice por array
data.iloc[1]

'b'

In [428]:
# iloc  indexing y slicing con indice por array
data.iloc[1:3]

3    b
5    c
dtype: object

In [429]:
# crear Serie comom dict {'key':'value}
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'Florida': 170312, 'New York': 141297,
                  'Pennsylvania': 119280})
# crear Serie comom dict {'key':'value}
pop = pd.Series({'California': 39538223, 'Texas': 29145505,
                 'Florida': 21538187, 'New York': 20201249,
                 'Pennsylvania': 13002700})
# crear DataFrame como dict con valores de Series
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [430]:
# indexing por nombre columna (acceder a Serie)
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [431]:
# indexing con atributo por columna
data.area


California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [432]:
# crear nueva columna a partir de otras columnas
data['density'] = data['pop'] / data['area']
data

area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

In [433]:
data

area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

In [434]:
data.values

array([[4.23967000e+05, 3.95382230e+07, 9.32577842e+01],
       [6.95662000e+05, 2.91455050e+07, 4.18960717e+01],
       [1.70312000e+05, 2.15381870e+07, 1.26463121e+02],
       [1.41297000e+05, 2.02012490e+07, 1.42970120e+02],
       [1.19280000e+05, 1.30027000e+07, 1.09009893e+02]])

In [435]:
# matriz transpuesta de DataFrame
data.T

California         Texas       Florida      New York  Pennsylvania
area     4.239670e+05  6.956620e+05  1.703120e+05  1.412970e+05  1.192800e+05
pop      3.953822e+07  2.914550e+07  2.153819e+07  2.020125e+07  1.300270e+07
density  9.325778e+01  4.189607e+01  1.264631e+02  1.429701e+02  1.090099e+02

In [98]:
# crear Series como dict
record1 = pd.Series({'Name': 'Alice',
                        'Class': 'Physics',
                        'Score': 85})
record2 = pd.Series({'Name': 'Jack',
                        'Class': 'Chemistry',
                        'Score': 82})
record3 = pd.Series({'Name': 'Helen',
                        'Class': 'Biology',
                        'Score': 90})

record1,record2,record3

(Name       Alice
 Class    Physics
 Score         85
 dtype: object,
 Name          Jack
 Class    Chemistry
 Score           82
 dtype: object,
 Name       Helen
 Class    Biology
 Score         90
 dtype: object)

In [437]:
# crear DataFrame([Series],index[i])
df = pd.DataFrame([record1, record2, record3],
                  index=['school1', 'school2', 'school1'])

df

Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [438]:
# crear DataFrame como lista de dict
# dict de cada fila

students = [{'Name': 'Alice',
              'Class': 'Physics',
              'Score': 85},
            {'Name': 'Jack',
             'Class': 'Chemistry',
             'Score': 82},
            {'Name': 'Helen',
             'Class': 'Biology',
             'Score': 90}]

# crear DataFrame (lista de dict, index=[i])
df = pd.DataFrame(students, index=['school1', 'school2', 'school1'])
# And lets print the head again
df

Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [439]:
# extraer fila[indice]
df.loc['school2']
df.loc['school1']

Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90

In [440]:
# extraer fila,columna
df.loc['school1', 'Name']


school1    Alice
school1    Helen
Name: Name, dtype: object

In [441]:
# transponer =cambiar indices-nombre columnas
df.T

school1    school2  school1
Name     Alice       Jack    Helen
Class  Physics  Chemistry  Biology
Score       85         82       90

In [442]:
# extraer columna
df['Name'],type(df['Name'])

(school1    Alice
 school2     Jack
 school1    Helen
 Name: Name, dtype: object,
 pandas.core.series.Series)

In [443]:
# extraer [fila][columna]
df.loc['school1']['Name']

school1    Alice
school1    Helen
Name: Name, dtype: object

In [444]:
# extraer todas las filas, columnas[]
df.loc[:,['Name','Score']]

Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

In [445]:
# crear nuevo DataFrame con fila eliminada
df.drop('school1')

Name      Class  Score
school2  Jack  Chemistry     82

In [446]:
df

Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [447]:
# copia de DataFrame
copy_df = df.copy()
# drop columna "column", inplace=True, axis=1[columna]
copy_df.drop("Name", inplace=True, axis=1)
copy_df

Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90

In [448]:
# eliminar columna con indexing
del df['Class']

In [449]:
df

Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

In [450]:
# crear nueva columna
df['ClassRanking'] =  None
df

Name  Score ClassRanking
school1  Alice     85         None
school2   Jack     82         None
school1  Helen     90         None

## Indexing

In [453]:
# cargar base de datos Admission_Predict
df = pd.read_csv('data/Admission_Predict.csv')

# visualizar datos
df.head()


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [99]:
# cargar base de datos .csv
# index_col=0  asigna primera columna como indice
df = pd.read_csv('data/Admission_Predict.csv', index_col=0)
#df.set_index('Serial No.',inplace=True)
df
#read_csv('datasets/Admission_Predict.csv', index_col=0)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
Serial No.                                                               
1                 337          118                  4  4.5   4.5  9.65   
2                 324          107                  4  4.0   4.5  8.87   
3                 316          104                  3  3.0   3.5  8.00   
4                 322          110                  3  3.5   2.5  8.67   
5                 314          103                  2  2.0   3.0  8.21   
...               ...          ...                ...  ...   ...   ...   
396               324          110                  3  3.5   3.5  9.04   
397               325          107                  3  3.0   3.5  9.11   
398               330          116                  4  5.0   4.5  9.45   
399               312          103                  3  3.5   4.0  8.78   
400               333          117                  4  5.0   4.0  9.66   

            Research  Chance of Admit   
Serial No.                              
1                  1              0.92  
2                  1              0.76  
3                  1              0.72  
4                  1              0.80  
5                  0              0.65  
...              ...               ...  
396                1              0.82  
397                1              0.84  
398                1              0.91  
399                0              0.67  
400                1              0.95  

[400 rows x 8 columns]

In [100]:
# cambiar nombre de columnas

# df.rename(columns={'columna anterior':'columna nueva'})
new_df=df.rename(columns={'GRE Score':'GRE Score', 'TOEFL Score':'TOEFL Score',
                   'University Rating':'University Rating', 
                   'SOP': 'Statement of Purpose','LOR': 'Letter of Recommendation',
                   'CGPA':'CGPA', 'Research':'Research',
                   'Chance of Admit':'Chance of Admit'})
new_df.head()


GRE Score  TOEFL Score  University Rating  Statement of Purpose  \
Serial No.                                                                    
1                 337          118                  4                   4.5   
2                 324          107                  4                   4.0   
3                 316          104                  3                   3.0   
4                 322          110                  3                   3.5   
5                 314          103                  2                   2.0   

            LOR   CGPA  Research  Chance of Admit   
Serial No.                                          
1            4.5  9.65         1              0.92  
2            4.5  8.87         1              0.76  
3            3.5  8.00         1              0.72  
4            2.5  8.67         1              0.80  
5            3.0  8.21         0              0.65

In [101]:
# columnas de nuevo DataFrame
new_df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'Statement of Purpose',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [102]:
# cambiar columnas, incluir espacio
new_df=new_df.rename(columns={'LOR ': 'Letter of Recommendation'})
new_df.head()

GRE Score  TOEFL Score  University Rating  Statement of Purpose  \
Serial No.                                                                    
1                 337          118                  4                   4.5   
2                 324          107                  4                   4.0   
3                 316          104                  3                   3.0   
4                 322          110                  3                   3.5   
5                 314          103                  2                   2.0   

            Letter of Recommendation  CGPA  Research  Chance of Admit   
Serial No.                                                              
1                                4.5  9.65         1              0.92  
2                                4.5  8.87         1              0.76  
3                                3.5  8.00         1              0.72  
4                                2.5  8.67         1              0.80  
5                                3.0  8.21         0              0.65

In [105]:
# cambiar nombre de las columnas, aplicar strip (quitar espacios) a los nombres de columnas 
new_df=new_df.rename(mapper=str.strip, axis='columns')
# Let's take a look at results
print(new_df.columns)
new_df

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'Statement of Purpose',
       'Letter of Recommendation', 'CGPA', 'Research', 'Chance of Admit'],
      dtype='object')


GRE Score  TOEFL Score  University Rating  Statement of Purpose  \
Serial No.                                                                    
1                 337          118                  4                   4.5   
2                 324          107                  4                   4.0   
3                 316          104                  3                   3.0   
4                 322          110                  3                   3.5   
5                 314          103                  2                   2.0   
...               ...          ...                ...                   ...   
396               324          110                  3                   3.5   
397               325          107                  3                   3.0   
398               330          116                  4                   5.0   
399               312          103                  3                   3.5   
400               333          117                  4                   5.0   

            Letter of Recommendation  CGPA  Research  Chance of Admit  
Serial No.                                                             
1                                4.5  9.65         1             0.92  
2                                4.5  8.87         1             0.76  
3                                3.5  8.00         1             0.72  
4                                2.5  8.67         1             0.80  
5                                3.0  8.21         0             0.65  
...                              ...   ...       ...              ...  
396                              3.5  9.04         1             0.82  
397                              3.5  9.11         1             0.84  
398                              4.5  9.45         1             0.91  
399                              4.0  8.78         0             0.67  
400                              4.0  9.66         1             0.95  

[400 rows x 8 columns]

In [108]:
# crear lista de nombre de columnas
cols = list(df.columns)

# list comprehension= for simplificado
# obj= [action for x in obj]
cols = [x.lower().strip() for x in cols] # pasar nombres de columnas a minuscula y separar
df.columns = cols
df

gre score  toefl score  university rating  sop  lor  cgpa  \
Serial No.                                                              
1                 337          118                  4  4.5  4.5  9.65   
2                 324          107                  4  4.0  4.5  8.87   
3                 316          104                  3  3.0  3.5  8.00   
4                 322          110                  3  3.5  2.5  8.67   
5                 314          103                  2  2.0  3.0  8.21   
...               ...          ...                ...  ...  ...   ...   
396               324          110                  3  3.5  3.5  9.04   
397               325          107                  3  3.0  3.5  9.11   
398               330          116                  4  5.0  4.5  9.45   
399               312          103                  3  3.5  4.0  8.78   
400               333          117                  4  5.0  4.0  9.66   

            research  chance of admit  
Serial No.                             
1                  1             0.92  
2                  1             0.76  
3                  1             0.72  
4                  1             0.80  
5                  0             0.65  
...              ...              ...  
396                1             0.82  
397                1             0.84  
398                1             0.91  
399                0             0.67  
400                1             0.95  

[400 rows x 8 columns]

# Manipulación

* chaining: varios métodos en cadena
* apply: aplicar metodo a DataFrame axis=1 filas, axis=0 columnas
* función lambda: aplicar función lambda axis=1 filas, axis=0 columnas
*


In [4]:
dfs=pd.read_html("https://en.wikipedia.org/wiki/College_admissions_in_the_United_States")
len(dfs)
dfs

[    0                                                  1
 0 NaN  This article has multiple issues. Please help ...
 1 NaN  This article contains instructions, advice, or...
 2 NaN  This article may contain an excessive amount o...,
     0                                                  1
 0 NaN  This article contains instructions, advice, or...,
     0                                                  1
 0 NaN  This article may contain an excessive amount o...,
    Unnamed: 0_level_0 Total (56 institutions)                     \
    Unnamed: 0_level_1      Unnamed: 1_level_1 Unnamed: 2_level_1   
     Admit Year (Fall)                    Apps             Admits   
 0                2001                  645111             198815   
 1                2002                  650908             202565   
 2                2003                  681989             206423   
 3                2004                  699074             207238   
 4                2005                  737493    

In [5]:
df = pd.read_csv('data/census.csv')
df

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME            CTYNAME  \
0         40       3         6      1       0  Alabama            Alabama   
1         50       3         6      1       1  Alabama     Autauga County   
2         50       3         6      1       3  Alabama     Baldwin County   
3         50       3         6      1       5  Alabama     Barbour County   
4         50       3         6      1       7  Alabama        Bibb County   
...      ...     ...       ...    ...     ...      ...                ...   
3188      50       4         8     56      37  Wyoming  Sweetwater County   
3189      50       4         8     56      39  Wyoming       Teton County   
3190      50       4         8     56      41  Wyoming       Uinta County   
3191      50       4         8     56      43  Wyoming    Washakie County   
3192      50       4         8     56      45  Wyoming      Weston County   

      CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  \
0           4779736            4780127          4785161  ...   
1             54571              54571            54660  ...   
2            182265             182265           183193  ...   
3             27457              27457            27341  ...   
4             22915              22919            22861  ...   
...             ...                ...              ...  ...   
3188          43806              43806            43593  ...   
3189          21294              21294            21297  ...   
3190          21118              21118            21102  ...   
3191           8533               8533             8545  ...   
3192           7208               7208             7181  ...   

      RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0             0.002295         -0.193196          0.381066          0.582002   
1             7.242091         -2.915927         -3.012349          2.265971   
2            14.832960         17.647293         21.845705         19.243287   
3            -4.728132         -2.500690         -7.056824         -3.904217   
4            -5.527043         -5.068871         -6.201001         -0.177537   
...                ...               ...               ...               ...   
3188          1.072643         16.243199         -5.339774        -14.252889   
3189         -1.589565          0.972695         19.525929         14.143021   
3190        -17.755986         -4.916350         -6.902954        -14.215862   
3191        -11.637475         -0.827815         -2.013502        -17.781491   
3192        -11.752361         -8.040059         12.372583          1.533635   

      RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0            -0.467369     1.030015     0.826644     1.383282     1.724718   
1            -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2            17.197872    15.844176    18.559627    22.727626    20.317142   
3           -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4             0.177258    -5.088389    -4.363636    -5.403729     0.754533   
...                ...          ...          ...          ...          ...   
3188        -14.248864     1.255221    16.243199    -5.295460   -14.075283   
3189         -0.564849     0.654527     2.408578    21.160658    16.308671   
3190        -12.127022   -18.136812    -5.536861    -7.521840   -14.740608   
3191          1.682288   -11.990126    -1.182592    -2.250385   -18.020168   
3192          6.935294   -12.032179    -8.040059    12.372583     1.533635   

      RNETMIG2015  
0        0.712594  
1       -2.187333  
2       18.293499  
3      -10.543299  
4        1.107861  
...           ...  
3188   -14.070195  
3189     1.520747  
3190   -12.606351  
3191     1.441961  
3192     6.935294  

[3193 rows x 100 columns]

In [6]:
# chaining

# where(condicion) filas con condicion ['SUMLEV']==50
# dropna() quitar NA's
# set_index([columns] determinar indice como columnas ['STNAME','CTYNAME']
# rename(columns={'old_column':'new_column'})    cambiar nombre de columnas 

(df.where(df['SUMLEV']==50)
    .dropna()
    .set_index(['STNAME','CTYNAME'])
    .rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'}))

df

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME            CTYNAME  \
0         40       3         6      1       0  Alabama            Alabama   
1         50       3         6      1       1  Alabama     Autauga County   
2         50       3         6      1       3  Alabama     Baldwin County   
3         50       3         6      1       5  Alabama     Barbour County   
4         50       3         6      1       7  Alabama        Bibb County   
...      ...     ...       ...    ...     ...      ...                ...   
3188      50       4         8     56      37  Wyoming  Sweetwater County   
3189      50       4         8     56      39  Wyoming       Teton County   
3190      50       4         8     56      41  Wyoming       Uinta County   
3191      50       4         8     56      43  Wyoming    Washakie County   
3192      50       4         8     56      45  Wyoming      Weston County   

      CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  \
0           4779736            4780127          4785161  ...   
1             54571              54571            54660  ...   
2            182265             182265           183193  ...   
3             27457              27457            27341  ...   
4             22915              22919            22861  ...   
...             ...                ...              ...  ...   
3188          43806              43806            43593  ...   
3189          21294              21294            21297  ...   
3190          21118              21118            21102  ...   
3191           8533               8533             8545  ...   
3192           7208               7208             7181  ...   

      RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0             0.002295         -0.193196          0.381066          0.582002   
1             7.242091         -2.915927         -3.012349          2.265971   
2            14.832960         17.647293         21.845705         19.243287   
3            -4.728132         -2.500690         -7.056824         -3.904217   
4            -5.527043         -5.068871         -6.201001         -0.177537   
...                ...               ...               ...               ...   
3188          1.072643         16.243199         -5.339774        -14.252889   
3189         -1.589565          0.972695         19.525929         14.143021   
3190        -17.755986         -4.916350         -6.902954        -14.215862   
3191        -11.637475         -0.827815         -2.013502        -17.781491   
3192        -11.752361         -8.040059         12.372583          1.533635   

      RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0            -0.467369     1.030015     0.826644     1.383282     1.724718   
1            -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2            17.197872    15.844176    18.559627    22.727626    20.317142   
3           -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4             0.177258    -5.088389    -4.363636    -5.403729     0.754533   
...                ...          ...          ...          ...          ...   
3188        -14.248864     1.255221    16.243199    -5.295460   -14.075283   
3189         -0.564849     0.654527     2.408578    21.160658    16.308671   
3190        -12.127022   -18.136812    -5.536861    -7.521840   -14.740608   
3191          1.682288   -11.990126    -1.182592    -2.250385   -18.020168   
3192          6.935294   -12.032179    -8.040059    12.372583     1.533635   

      RNETMIG2015  
0        0.712594  
1       -2.187333  
2       18.293499  
3      -10.543299  
4        1.107861  
...           ...  
3188   -14.070195  
3189     1.520747  
3190   -12.606351  
3191     1.441961  
3192     6.935294  

[3193 rows x 100 columns]

In [7]:
# metodos 'manual'
df = df[df['SUMLEV']==50] # filas por condicion ['SUMLEV']==50
df.set_index(['STNAME','CTYNAME'], inplace=True) # determinar indices  ['STNAME','CTYNAME']
df.rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'}) # cambiar nombres de columnas

SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME                                                      
Alabama Autauga County         50       3         6      1       1   
        Baldwin County         50       3         6      1       3   
        Barbour County         50       3         6      1       5   
        Bibb County            50       3         6      1       7   
        Blount County          50       3         6      1       9   
...                           ...     ...       ...    ...     ...   
Wyoming Sweetwater County      50       4         8     56      37   
        Teton County           50       4         8     56      39   
        Uinta County           50       4         8     56      41   
        Washakie County        50       4         8     56      43   
        Weston County          50       4         8     56      45   

                           CENSUS2010POP  Estimates Base 2010  \
STNAME  CTYNAME                                                 
Alabama Autauga County             54571                54571   
        Baldwin County            182265               182265   
        Barbour County             27457                27457   
        Bibb County                22915                22919   
        Blount County              57322                57322   
...                                  ...                  ...   
Wyoming Sweetwater County          43806                43806   
        Teton County               21294                21294   
        Uinta County               21118                21118   
        Washakie County             8533                 8533   
        Weston County               7208                 7208   

                           POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
STNAME  CTYNAME                                                                
Alabama Autauga County               54660            55253            55175   
        Baldwin County              183193           186659           190396   
        Barbour County               27341            27226            27159   
        Bibb County                  22861            22733            22642   
        Blount County                57373            57711            57776   
...                                    ...              ...              ...   
Wyoming Sweetwater County            43593            44041            45104   
        Teton County                 21297            21482            21697   
        Uinta County                 21102            20912            20989   
        Washakie County               8545             8469             8443   
        Weston County                 7181             7114             7065   

                           ...  RDOMESTICMIG2011  RDOMESTICMIG2012  \
STNAME  CTYNAME            ...                                       
Alabama Autauga County     ...          7.242091         -2.915927   
        Baldwin County     ...         14.832960         17.647293   
        Barbour County     ...         -4.728132         -2.500690   
        Bibb County        ...         -5.527043         -5.068871   
        Blount County      ...          1.807375         -1.177622   
...                        ...               ...               ...   
Wyoming Sweetwater County  ...          1.072643         16.243199   
        Teton County       ...         -1.589565          0.972695   
        Uinta County       ...        -17.755986         -4.916350   
        Washakie County    ...        -11.637475         -0.827815   
        Weston County      ...        -11.752361         -8.040059   

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STNAME  CTYNAME                                                 
Alabama Autauga County            -3.012349          2.265971   
        Baldwin County            21.845705         19.243287   
        Barbour County            -7.056824         -3.904

In [9]:
# apply: aplicar función a DataFrame
# axis=1 filas, axis=0 columnas

# función min_max
# aplicar min_max sobre columnas ['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']
# returns Serie min, max
def min_max(fila):
    data = fila[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    return pd.Series({'min': np.min(data), 'max': np.max(data)})

# aplicar función min_max
# df.apply(funcion, axis) 
df.apply(min_max, axis=1)


min       max
STNAME  CTYNAME                              
Alabama Autauga County      54660.0   55347.0
        Baldwin County     183193.0  203709.0
        Barbour County      26489.0   27341.0
        Bibb County         22512.0   22861.0
        Blount County       57373.0   57776.0
...                             ...       ...
Wyoming Sweetwater County   43593.0   45162.0
        Teton County        21297.0   23125.0
        Uinta County        20822.0   21102.0
        Washakie County      8316.0    8545.0
        Weston County        7065.0    7234.0

[3142 rows x 2 columns]

In [16]:
# columnas sobre las que se aplica la función lamba
rows = ['POPESTIMATE2010',
        'POPESTIMATE2011',
        'POPESTIMATE2012',
        'POPESTIMATE2013',
        'POPESTIMATE2014',
        'POPESTIMATE2015']

# aplicar función lambda 

# lambda
# funcion: np.max(x[rows]
# axis=1: filas 
df.apply(lambda x: np.max(x[rows]), axis=1)


0       4858979
1         55347
2        203709
3         27341
4         22861
         ...   
3188      45162
3189      23125
3190      21102
3191       8545
3192       7234
Length: 3193, dtype: int64

In [17]:
df = pd.read_csv('data/census.csv')

# función región
# returns región de cada estado

def get_state_region(x):
    northeast = ['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 
                 'Rhode Island','Vermont','New York','New Jersey','Pennsylvania']
    midwest = ['Illinois','Indiana','Michigan','Ohio','Wisconsin','Iowa',
               'Kansas','Minnesota','Missouri','Nebraska','North Dakota',
               'South Dakota']
    south = ['Delaware','Florida','Georgia','Maryland','North Carolina',
             'South Carolina','Virginia','District of Columbia','West Virginia',
             'Alabama','Kentucky','Mississippi','Tennessee','Arkansas',
             'Louisiana','Oklahoma','Texas']
    west = ['Arizona','Colorado','Idaho','Montana','Nevada','New Mexico','Utah',
            'Wyoming','Alaska','California','Hawaii','Oregon','Washington']
    
    if x in northeast:
        return "Northeast"
    elif x in midwest:
        return "Midwest"
    elif x in south:
        return "South"
    else:
        return "West"
    
    
df['state_region'] = df['STNAME'].apply(lambda x: get_state_region(x))
df

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME            CTYNAME  \
0         40       3         6      1       0  Alabama            Alabama   
1         50       3         6      1       1  Alabama     Autauga County   
2         50       3         6      1       3  Alabama     Baldwin County   
3         50       3         6      1       5  Alabama     Barbour County   
4         50       3         6      1       7  Alabama        Bibb County   
...      ...     ...       ...    ...     ...      ...                ...   
3188      50       4         8     56      37  Wyoming  Sweetwater County   
3189      50       4         8     56      39  Wyoming       Teton County   
3190      50       4         8     56      41  Wyoming       Uinta County   
3191      50       4         8     56      43  Wyoming    Washakie County   
3192      50       4         8     56      45  Wyoming      Weston County   

      CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  \
0           4779736            4780127          4785161  ...   
1             54571              54571            54660  ...   
2            182265             182265           183193  ...   
3             27457              27457            27341  ...   
4             22915              22919            22861  ...   
...             ...                ...              ...  ...   
3188          43806              43806            43593  ...   
3189          21294              21294            21297  ...   
3190          21118              21118            21102  ...   
3191           8533               8533             8545  ...   
3192           7208               7208             7181  ...   

      RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  RDOMESTICMIG2015  \
0            -0.193196          0.381066          0.582002         -0.467369   
1            -2.915927         -3.012349          2.265971         -2.530799   
2            17.647293         21.845705         19.243287         17.197872   
3            -2.500690         -7.056824         -3.904217        -10.543299   
4            -5.068871         -6.201001         -0.177537          0.177258   
...                ...               ...               ...               ...   
3188         16.243199         -5.339774        -14.252889        -14.248864   
3189          0.972695         19.525929         14.143021         -0.564849   
3190         -4.916350         -6.902954        -14.215862        -12.127022   
3191         -0.827815         -2.013502        -17.781491          1.682288   
3192         -8.040059         12.372583          1.533635          6.935294   

      RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015  \
0        1.030015     0.826644     1.383282     1.724718     0.712594   
1        7.606016    -2.626146    -2.722002     2.592270    -2.187333   
2       15.844176    18.559627    22.727626    20.317142    18.293499   
3       -4.874741    -2.758113    -7.167664    -3.978583   -10.543299   
4       -5.088389    -4.363636    -5.403729     0.754533     1.107861   
...           ...          ...          ...          ...          ...   
3188     1.255221    16.243199    -5.295460   -14.075283   -14.070195   
3189     0.654527     2.408578    21.160658    16.308671     1.520747   
3190   -18.136812    -5.536861    -7.521840   -14.740608   -12.606351   
3191   -11.990126    -1.182592    -2.250385   -18.020168     1.441961   
3192   -12.032179    -8.040059    12.372583     1.533635     6.935294   

      state_region  
0            South  
1            South  
2            South  
3            South  
4            South  
...            ...  
3188          West  
3189          West  
3190          West  
3191          West  
3192          West  

[3193 rows x 101 columns]

# Merging 

merge() para manipular conjuntos Sets A-B

union   parametro how= 'outer' pd.merge(A, B, how = 'outer', left_index = True, right_index = True)

interseccion  parametro how= 'inner'  pd.merge(A, B, how = 'inner', left_index = True, right_index = True)

addicion de todos los elementos de A asi esten en interseccion

pd.merge(A, B, how = 'left', left_index = True, right_index = True)

merge() pero utilizando columnas en especifico para hacer merge

pd.merge(staff_df, std_df, how = 'right', on='Name')

concat()  to concatenate DataFrames

df_list = [df_A, df_B]

pd.concat(df_list)

In [462]:
# crear DataFrames
staff_df = pd.DataFrame([{'Name':'Kelly', 'Role':'Director of HR'},
                        {'Name':'Sally', 'Role':'Course liasion'},
                        {'Name':'James', 'Role':'Grader'}])
# create students df
std_df = pd.DataFrame([{'Name':'James', 'School':'Business'},
                      {'Name':'Mike', 'School':'Law'},
                      {'Name':'Sally', 'School':'Engineering'}])
# index staff by column Name
staff_df = staff_df.set_index('Name')
std_df = std_df.set_index('Name')

print(staff_df)
print(std_df)


                 Role
Name                 
Kelly  Director of HR
Sally  Course liasion
James          Grader
            School
Name              
James     Business
Mike           Law
Sally  Engineering


# Funciones y Manipulación de DataFranes

DataFrames Functions and Manipulation


Merging DataFrames: unir DataFrame (union, intersection) by column

Apply function:  df.apply(function, axis='columns'),  aplicar function a un DataFrame

Lambda function

lambda:  df.apply(lambda x: method(x[rows]), axis=1),  aplicar function a rows
del DataFrame

Method chain, to condense multiple operations on a DataFrame

Pandas Idioms
df.where(),  filtra el DataFrame con condiciones, si no cumple entonces value NaN ( hay que hacer df.dropnan() manual)

df.where() NO CAMBIA EL DataFrame original, solo crea una instancia del anterior

df.dropnan(),  para quitar las filas con NaN

df.set_index(key='column'),  para hacer index del DataFrame una columna

df.rename(columns={'key_old':'key_new'})),  cambiar los key de las columnas


Groupby(),  agrupar DataFrame por columnas (set index)

groupby(),  for column, projected DataFrame 

for group, frame in df.groupby(['STNAME']):  
    avg = np.average(frame['CENSUS2010POP'])
    print(group, str(avg) ) 
    
aggregate() parametro  df.aggregate({column1:method_n, column2:method_n}),  returns DataFrame con columnas column-n, aplicando el metodo method-n

filter() df.filter(lambda  x: method(x:['column'])),  filtrar valores sobre columnas del DataFrame

apply() df.apply(method),  aplica un metodo sobre todo el DataFrame

df.groupby([column]),  agrupar DataFrame por columnas(set index)

groupby([column])

value frame es projected DataFrame del metodo

for group, frame in df.groupby([column]):
    # print(group, str(avg) ) 
    
Aggregation(),  returns DataFrame en las columnas columns-n, aplicando las funciones a las respectivas columnas

df.aggregate({'column-n':(function-n)})

Transformation(),  returns DataFrame con function aplicada

trans_df = df[cols].groupby(column).transform(function)

Filter(), filtra DataFrame aplicando lambda function on condition (function)

df.filter(lambda x: function(x[columns, on condition])>X)

Pivot Table: sub-table de DataFrame, usando aggfunc=[func-n], values = vals,
index = column_index, columns = columns_cols

multiple aggfunc() using pivot_table

piv_table = df.pivot_table(values = vals, index = column_index, columns = 

columns_cols, aggfunc=[func-1,func-n])


# Exploración de Bases de datos

In [463]:
# ver
df


gre score  toefl score  university rating  sop  lor  cgpa  \
Serial No.                                                              
1                 337          118                  4  4.5  4.5  9.65   
2                 324          107                  4  4.0  4.5  8.87   
3                 316          104                  3  3.0  3.5  8.00   
4                 322          110                  3  3.5  2.5  8.67   
5                 314          103                  2  2.0  3.0  8.21   
...               ...          ...                ...  ...  ...   ...   
396               324          110                  3  3.5  3.5  9.04   
397               325          107                  3  3.0  3.5  9.11   
398               330          116                  4  5.0  4.5  9.45   
399               312          103                  3  3.5  4.0  8.78   
400               333          117                  4  5.0  4.0  9.66   

            research  chance of admit  
Serial No.                             
1                  1             0.92  
2                  1             0.76  
3                  1             0.72  
4                  1             0.80  
5                  0             0.65  
...              ...              ...  
396                1             0.82  
397                1             0.84  
398                1             0.91  
399                0             0.67  
400                1             0.95  

[400 rows x 8 columns]